import './globals.css'
import Header from './Header'
import { GlobalContextProvider, useGlobalContext } from './Context/store'
import Sidebar from './Sidebar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <GlobalContextProvider>
        <Header />
        <div>
            {children}
        </div>
        </GlobalContextProvider>
      </body>

    </html>
  )
}
