import './globals.css'
import Header from './Header'
import { GlobalContextProvider, useGlobalContext } from './Context/store'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div>
          <GlobalContextProvider>
            {children}
          </GlobalContextProvider>
        </div>
      </body>

    </html>
  )
}
