import './globals.css'
import Header from './Header'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-[#050023]'>
        <Header />
        <div>{children}</div>
      </body>

    </html>
  )
}
